### ISSUE TITLE
CS 1.5.0 doc checklist

### ISSUE THREAD

**Issue by michellep-basho** [basho/basho_docs#1178]
Feel free to edit this. I didn't include the bugs or optimizations not on the radar of customers.
- [x] Multi-bag (multi-PB) support (flag as tech preview)
- [x]  riak-cs-debug
- [x]  riak-cs-admin
- [x]  riak-cs-stanchion
- [x] Syslog support through lager_syslog
- [x] S3 API changes: PUT object Copy (with caveat that it's not yet supported by the Swift API), multi-DELETE, Cache Control headers
- [x] Ability to set ACLs upon PUT object request (existed but was broken, so may already be documented in 1.4)
- [x] Garbage collection improvements (tech debt, but may want to address config at least)?
- [x] Configuration option(s) for features that can only be used with Riak 1.5
- [x] Update version compatibility page => #1063
- [x] Fix CS install docs (especially for Mac OS X)
- [x] New default value for ‘gc_paginated_indexes’
- [x] Stanchion upgrades as appropriate for existing docs (see Kota's comment) --- _As confirmed by Kota, no docs updates necessary at this time_

Time permitting
- [x] Address ‘connection_pools’ attributes (https://github.com/basho/riak_cs/issues/752)
- [ ] Add kernel tuning advice (https://github.com/basho/riak_cs/issues/660)

https://github.com/basho/riak_cs/blob/release/1.5/RELEASE-NOTES.md#riak-cs-150-release-notes
