### ISSUE TITLE
2.0 docs checklist

### ISSUE THREAD

**Issue by macintux** [basho/basho_docs#593]
- [ ] `allow_mult=true` by default
- [ ] CRDTs
- [ ] Search 2 (codename Yokozuna)
- [ ] Deprecate Legacy Search
- [ ] Strong consistency
- [ ] New configuration (cuttlefish)
- [ ] Bucket types
- [ ] Authentication/security
- [ ] Ring resizing
- [ ] Removing HTTP support from clients in favor of PB
## Enterprise
- [ ] Handle dead clusterid's for replicated CS manifests
- [ ] Riak CS bucket replication controls
