### ISSUE TITLE
Riak 2.0 docs checklist

### ISSUE THREAD

**Issue by lucperkins** [basho/basho_docs#736]
- [ ] Convert `curl` examples into real-life code examples
- [ ] Begin porting to `riak.conf` from `app.config`
- [ ] `allow_mult=true` by default (probably a whole doc by itself)
- [ ] CRDTs = Data Types
- [ ] Yokozuna = Riak Search
- [ ] Strong consistency
- [ ] Bucket types (page that explains what bucket types are and why we need them so that other pages can link to it)
- [ ] Authentication/security (definitely needs its own document)
- [ ] Ring resizing (riak/ops)
